---

- name: Create logstash input file
  template: src=logstash.conf.j2 dest={{ logstash_conf_dir }}/zabbix-agent.conf owner=root group=root mode=0644
  when: zabbix_agent_use_logstash
  notify:
    - restart logstash
  tags:
    - logstash
    - zabbix-agent
